export { default as Caveats } from './Caveats'
export { default as SpecialThanks } from './SpecialThanks'
export { default as AboutMe } from './AboutMe'
export { default as Goals } from './Goals'
export { default as Motivation } from './Motivation'
export { default as GetStartedButton } from './GetStartedButton'
export { default as Highlights } from './Highlights'
