name: CI (Pull Request)

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run Linting & Style Checks
        run: bun run lint

      - name: Run Formatter
        run: bun run format

      - name: Run Tests with Coverage
        run: bun test --coverage
