name: Setup Bun

on:
  workflow_call:
    

jobs:
  setup:
    name: setup bun & install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
