name: Test & Comment Test Coverage on PR

on:
  pull_request: 
    types:
      - opened
      - synchronize

jobs:
  test: 
    name: Run Tests with Coverage & Comment on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run Tests with Coverage
        run: bun test --coverage

      - name: Capture and Comment Coverage
        run: |
          coverage_output=$(bun test --coverage)
          echo "$coverage_output" | gh pr comment https://github.com/$GITHUB_REPOSITORY/pull/$PR_NUMBER --body -
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
